---

group: stable
dist: trusty
branches:
  only:
    - develop
    - master

language: python
python: "2.7"

env:
  - ANSIBLE_INSTALL_VERSION=2.0.2.0
  - ANSIBLE_INSTALL_VERSION=2.1.4.0
  - ANSIBLE_INSTALL_VERSION=2.2.1.0

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo /etc/init.d/mysql stop
  - sudo apt-get purge -y "mysql-*"
  - sudo rm -rf /var/lib/mysql/
  - sudo userdel -r mysql

install:
  # Install Ansible.
  - pip install ansible==${ANSIBLE_INSTALL_VERSION} ansible-lint

script:
  # Install Role Dependencies
  - make test_deps
  # Lint
  - make lint
  # Test Ansible role
  - make test_ansible

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
