---

- name: Looks for extra MySQL settings
  become: yes
  stat:
    path: /etc/mysql/conf.d/custom.cnf
  register: custom_cnf

- name: Configure local MySQL root user password
  become: yes
  mysql_user:
    login_host: localhost
    login_user: "{{ sansible_mysql_root_user }}"
    login_password: ""
    name: "{{ sansible_mysql_root_user }}"
    password: "{{ sansible_mysql_root_password }}"
    state: present
  when:
    - not custom_cnf.stat.exists
    - "ansible_virtualization_type != 'docker'"

- name: Remove anonymous user
  mysql_user:
    login_host: localhost
    login_password: ""
    login_user: "{{ sansible_mysql_root_user }}"
    name: ""
    state: absent
  when:
    - not custom_cnf.stat.exists
    - "ansible_virtualization_type != 'docker'"

- name: Configure cusom MySQL client options
  become: yes
  template:
    src: custom.cnf.j2
    dest: /etc/mysql/conf.d/custom.cnf
  notify:
    - restart mysql
