---

- name: Ensure MySQL server and supporting packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "mysql-server={{ sansible_mysql_version }}"
    - python-mysqldb
